name: "HomeEntity"
main: "cn.thelama.homeent.HomeEntity"
version: 1.4
commands:
  hent:

  warp:

  show:

  back:

  session:

  exit:

  slime:

  prefix:

  tpa:

  tphere:

  tpaccept:

  tpdeny:

  relay: