name: "HomeEntity"
main: "cn.thelama.homeent.HomeEntity"
version: 1.6.0
commands:
  hent:

  warp:

  show:

  back:

  auth:

  admin:

  exit:

  slime:

  prefix:

  tpa:

  tphere:

  tpaccept:

  tpdeny:

  relay:

  home:

  sethome:

  cat:

  feed:

  motd: