name: Gradle Package

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Generate build.yml
        run: |
          echo "初始化信息生成脚本..."

          version=$(cat ${GITHUB_WORKSPACE}/src/main/resources/version)
          echo "版本: $version"

          echo "将构建信息写入build.yml..."

          echo "repo: $GITHUB_REPOSITORY" >> "${GITHUB_WORKSPACE}/src/main/resources/build.yml"
          echo "仓库: $GITHUB_REPOSITORY"
          echo "branch: $GITHUB_HEAD_REF" >> "${GITHUB_WORKSPACE}/src/main/resources/build.yml"
          echo "分支: $GITHUB_HEAD_REF"
          echo "id: $GITHUB_RUN_NUMBER" >> "${GITHUB_WORKSPACE}/src/main/resources/build.yml"
          echo "构建号: $GITHUB_RUN_NUMBER"
          echo "hash: $GITHUB_SHA" >> "${GITHUB_WORKSPACE}/src/main/resources/build.yml"
          echo "提交哈希: $GITHUB_SHA"
          echo "github: $GITHUB_API_URL" >> "${GITHUB_WORKSPACE}/src/main/resources/build.yml"
          echo "Github 接口URL: $GITHUB_API_URL"

          echo "替换版本信息..."

          ConstantReplacer @version $version ${GITHUB_WORKSPACE}/src

      - name: Build with Gradle
        run: gradle shadowJar

      # The USERNAME and TOKEN need to correspond to the credentials environment variables used in
      # the publishing section of your build.gradle
      - name: Publish to GitHub Packages
        run: gradle publish
        env:
          GH_ACTOR: ${{ github.actor }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
